name: habit_time_tracker

services:
  habit_time_tracker-postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: habit_time_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - habit_time_tracker_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: ["postgres", "-c", "port=5433"]

volumes:
  habit_time_tracker_pgdata:
